# Generated by Django 4.1.7 on 2023-03-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psutelegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('language_code', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(default='f'),
            preserve_default=False,
        ),
    ]
