# Generated by Django 4.1.7 on 2023-03-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psutelegrambot', '0006_telegramuser_rate_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='rate_limit',
        ),
    ]
