# Generated by Django 4.1.7 on 2023-04-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psutelegrambot', '0010_alter_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotFoundQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('question_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
