# Generated by Django 4.1.7 on 2023-04-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psutelegrambot', '0011_usernotfoundquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotfoundquestion',
            name='isIssueResolved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotfoundquestion',
            name='user_langauage_code',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
