# Generated by Django 4.1.7 on 2023-04-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psutelegrambot', '0012_usernotfoundquestion_isissueresolved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotfoundquestion',
            old_name='user_langauage_code',
            new_name='user_language_code',
        ),
    ]
