# Generated by Django 4.1.7 on 2023-04-02 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psutelegrambot', '0013_rename_user_langauage_code_usernotfoundquestion_user_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotfoundquestion',
            name='question_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
