# Generated by Django 4.1.7 on 2023-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psutelegrambot', '0016_remove_usernotfoundquestion_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
